apiVersion: v1
kind: Endpoints
metadata:
  name: simple-endpoint
subsets:
  - addresses:
    - ip: 74.125.68.102 # ip của pod hay service nào đó
    ports:
      - name: http
        port: 80
        protocol: TCP
