apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-2
spec:
  type: ClusterIP
  ports:
    - name: nginx
      port: 80 # port của service
      targetPort: 80 # trỏ tới port của pod
    - name: redis
      port: 6379
      targetPort: 6379
