apiVersion: v1
kind: Service
metadata:
  name: node-port
spec:
  type: NodePort
  selector:
    environment: staging
  ports:
    - name: http
      port: 80 # port của service sẽ tạo. Tức service khi tạo sẽ có port 80
      targetPort: 80 # target tới port của container
      nodePort: 30000 # port của node mình tự định nghĩa. user bên ngoài dùng port này có thể giao tiếp
